In [25]:
# D. Scott
# Linear Algebra: TCI
# Code Challenge 11.1
# Verify that determinant of scaled matrix is same as determinant of
# matrix scaled by scaling factor * number of rows in matrix

import random
import numpy as np

# generate random 4 x 4 matrix
num1 = []
for i in range(0,16):
    num1.append(random.randint(0,10))
A = np.array(num1).reshape(4,4)

print("A:\n",A)

beta = random.randint(-10,-1)
print("beta = ",beta)

print("det(beta*A) = ",np.linalg.det(beta*A))
print("beta^4*det(A) = ",np.linalg.det(A)*beta**4)

A:
 [[10  7  5  4]
 [ 4  3  6  0]
 [ 9  0  2 10]
 [10  0 10  7]]
beta =  -6
det(beta*A) =  -428975.99999999994
beta^4*det(A) =  -428976.0
