In [9]:
# D. Scott
# Linear Algebra: TCI
# Coding Challenge 5.2

import random
import numpy as np

matrix = []

# generate dense matrix with random numbers
for i in range(0,6):
    row = []
    for j in range(0,6):
        row.append(random.randint(1,8))
    matrix.append(row)

matrix = np.array(matrix)
    
print(matrix)

# extract upper and lower triangulars from matrix
upper = np.triu(matrix)
lower = np.tril(matrix)

# transpose upper and lower diagonals
u_t = upper.transpose()
l_t = lower.transpose()

# add upper and lower triangulars
u_plus_l = upper+lower

# add upper and lower transpositions
u_t_plus_l_t = u_t + l_t

# add previous two sums
result = u_plus_l + u_t_plus_l_t

print("\nSymmetric matrix: \n",result)


[[2 6 8 8 2 8]
 [3 5 3 1 4 4]
 [1 4 1 5 6 8]
 [5 1 5 4 3 7]
 [7 3 5 3 8 8]
 [2 5 2 7 5 6]]

Symmetric matrix: 
 [[ 8  9  9 13  9 10]
 [ 9 20  7  2  7  9]
 [ 9  7  4 10 11 10]
 [13  2 10 16  6 14]
 [ 9  7 11  6 32 13]
 [10  9 10 14 13 24]]
