In [4]:
# D. Scott
# Linear Algebra: TCI
# Coding Challenge 5.3

import random
import numpy as np

matrix = []

# generate 4 x 8 diagonal matrix
for i in range(0,4):
    row = []
    for j in range(0,8):
        if (i == j):
            row.append(i+1)
        else:
            row.append(0)
    matrix.append(row)

matrix = np.array(matrix)

# generate 8 x 4 diagonal matrix
matrix2 = []

for i in range(0,8):
    row = []
    for j in range(0,4):
        if (i == j):
            row.append(i+1)
        else:
            row.append(0)
    matrix2.append(row)

matrix2 = np.array(matrix2)
    
print("4x8 diagonal:\n",matrix)
print("\n8x4 diagonal:\n",matrix2)

4x8 diagonal:
 [[1 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0]
 [0 0 0 4 0 0 0 0]]

8x4 diagonal:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
