In [72]:
# D. Scott
# Linear Algebra: TCI
# Code Challenge 6.1
# Layer method of matrix multiplication

import random
import numpy as np

nums1 = []
nums2 = []

# generate random numbers
for i in range(0,8):
    nums1.append(random.randint(-4,12))
for i in range(0,12):
    nums2.append(random.randint(-4,12))

# populate matrices
m1 = np.array([[nums1[0],nums1[1],
               nums1[2],nums1[3]],
               [nums1[4],nums1[5],
               nums1[6],nums1[7]]])

m2 = np.array([[nums2[0],nums2[1],nums2[2]],
               [nums2[3],nums2[4],nums2[5]],
               [nums2[6],nums2[7],nums2[8]],
               [nums2[9],nums2[10],nums2[11]]])

print("Matrix A:\n",m1,"\n")
print("Matrix B:\n",m2,"\n")

count = 0

# create matrices for intemediary layers and overall sum
add_matrix = np.empty((2,3),dtype=int)
sum_matrix = np.zeros((2,3),dtype=int)

print("Layer matrices:")
# for each column in m1...
for col in range(0,4):
    # multiply by element in row of m2
    for el in range(0,3):
        new_column = np.array(m1[:,col])
        new_column *= m2[col][el]
        # build up intermediary matrix column by column
        add_matrix[:,el] = new_column
    # add the intermediary matrix to the sum
    sum_matrix += add_matrix
    print(add_matrix," \n")
    if (col != 3):
        print("\t+\n")
print("\t=\n",sum_matrix)


print("\nCheck: \n",m1@m2)
    

    


Matrix A:
 [[ 5  9  2 -2]
 [ 0 -2  9  8]] 

Matrix B:
 [[11 12  6]
 [ 5  6  0]
 [12  4 -2]
 [ 4 10 -2]] 

Layer matrices:
[[55 60 30]
 [ 0  0  0]]  

	+

[[ 45  54   0]
 [-10 -12   0]]  

	+

[[ 24   8  -4]
 [108  36 -18]]  

	+

[[ -8 -20   4]
 [ 32  80 -16]]  

	=
 [[116 102  30]
 [130 104 -34]]

Check: 
 [[116 102  30]
 [130 104 -34]]
