In [13]:
# D. Scott
# Linear Algebra: TCI
# Code Challenge 7.1
# Generate a random matrix of any particular rank

import random
import numpy as np

# generate and populate random matrices with same inner value
num1 = []
num2 = []
for i in range(0,12):
    num1.append(random.randint(-6,12))
for i in range(0,18):
    num2.append(random.randint(-6,12))
A = np.array(num1).reshape(4,3)
B = np.array(num2).reshape(3,6)

C = A@B

print("A:\n",A)
print("\nB:\n",B)
print("\nC=A@B:\n",C)

# inner value is the rank
print("\nRank(C): ",np.linalg.matrix_rank(C))

# second example
num1 = []
num2 = []
for i in range(0,16):
    num1.append(random.randint(-6,12))
for i in range(0,32):
    num2.append(random.randint(-6,12))
A = np.array(num1).reshape(2,8)
B = np.array(num2).reshape(8,4)

C = A@B

print("A:\n",A)
print("\nB:\n",B)
print("\nC=A@B:\n",C)

print("\nRank(C): ",np.linalg.matrix_rank(C))


A:
 [[-1 10  2]
 [-6 -2 -4]
 [ 3 -1  9]
 [ 0 -1 12]]

B:
 [[ 9  0  0 -4  4 12]
 [-2  4 -2 10  0  7]
 [ 2  1 10 12 -5 -1]]

C=A@B:
 [[-25  42   0 128 -14  56]
 [-58 -12 -36 -44  -4 -82]
 [ 47   5  92  86 -33  20]
 [ 26   8 122 134 -60 -19]]

Rank(C):  3
A:
 [[ 1  8 -1 10 -3 -6  9 -6]
 [ 2  1  2 11 -5 -6  1  2]]

B:
 [[ 2  8 -3  9]
 [-5 -4  4 11]
 [ 5 12 12 -2]
 [-3 -3  2  0]
 [-4 -5  6 -1]
 [-2  8  9 -5]
 [-4 11  9 -3]
 [ 2 10 12  9]]

C=A@B:
 [[-97 -60 -26  51]
 [  8  11  -7  75]]

Rank(C):  2
