In [1]:
# D. Scott
# Linear Algebra: TCI
# Code Challenge 7.2
# Generate full-rank random matrix

import random
import numpy as np

num = []
for i in range(0,25):
    num.append(random.randint(-6,12))
r_mat = np.array(num).reshape(5,5)

z = np.zeros((5,5),dtype=int)
eps = np.finfo(float).eps
print(z)
print("Rank: ",np.linalg.matrix_rank(z),"\n")
S = r_mat*eps
print(S)
print("Rank_summed: ",np.linalg.matrix_rank(z+S))



[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Rank:  0 

[[-1.11022302e-15  2.22044605e-15  2.22044605e-16 -2.22044605e-16
  -4.44089210e-16]
 [-4.44089210e-16  8.88178420e-16  2.66453526e-15 -6.66133815e-16
   2.66453526e-15]
 [ 1.55431223e-15  2.22044605e-16  2.66453526e-15  2.22044605e-16
  -8.88178420e-16]
 [-1.11022302e-15 -6.66133815e-16  2.66453526e-15  0.00000000e+00
  -4.44089210e-16]
 [ 1.77635684e-15  8.88178420e-16  1.55431223e-15 -1.33226763e-15
  -1.11022302e-15]]
Rank_summed:  5
