In [12]:
# D. Scott
# Linear Algebra: TCI
# Code Challenge 8.2
# Find null space/left null space basis dimensions and verify 
# summation to ambient dimensions

import random
import numpy as np
from scipy.linalg import null_space

# generate and populate random matrices with same inner value
num1 = []
num2 = []
for i in range(0,144):
    num1.append(random.randint(-6,12))
for i in range(0,99):
    num2.append(random.randint(-6,12))
A1 = np.array(num1).reshape(16,9)
A2 = np.array(num2).reshape(9,11)

A = A1@A2

print("A (16 x 11):\n",A,"\nRank(A) = ",np.linalg.matrix_rank(A))

n = null_space(A)
n_t = null_space(A.transpose())
print("\nNull space basis: \n",n)
print("\nLeft null space basis: \n",n_t)

print("\nNull space dim + row space dim = ",n.shape[1]," + ",np.linalg.matrix_rank(A)," = ",
      n.shape[1]+np.linalg.matrix_rank(A))
print("\nLeft null space dim + column space dim = ",n_t.shape[1]," + ",np.linalg.matrix_rank(A)," = ",
      n_t.shape[1]+np.linalg.matrix_rank(A))

A (16 x 11):
 [[-100    3   30   30 -182   57   22 -123   45   15  150]
 [ 109 -166  -95   -9  -56   72   45 -152  127  -81  -83]
 [ -34  145  169  -80  208  165  167   23   75  279  187]
 [ 136   73   24  129  -18  132  221 -118  254  128   74]
 [ 135  370  156  133  135  -30  156   30   55  113  139]
 [  76  216   91   14  346  161   59  142  152  219   56]
 [ 113   16  188  -77  291  268   -8   47   18  174  173]
 [ 159  -10   66    6  146  105   99  -73  100   98   22]
 [  82  -40   -8   20  149  117   24 -120  161  111  124]
 [ 229  158  212   -5  221  186  232  114   21  175  113]
 [ 297  230  243   87  270  244  235   70  120  228  199]
 [ 128  167  248   79  202  207  207   60   92  334  247]
 [ 160  136  104   74  198  131   78  212   55  131  -33]
 [  67  134  159   69  132  234   35   97   82  176  203]
 [  -1  108   17  -32  224  -30   54   -3   65  142   30]
 [  89   76   72   13  154   41  324   50  113  283   47]] 
Rank(A) =  9

Null space basis: 
 [[-0.35812762  0.27283