In [9]:
# D. Scott
# Linear Algebra: TCI
# Code Challenge 10.1
# Create all components of system of equations
# (variables, coefficients, constants)

import numpy as np

# create variables vector
soln = [-4,2,7.5]
soln = np.array(soln,dtype=float)

print("Variables: \n",soln)

# create coefficients matrix for system:
#    3x - y
#     x + 4y - z
#          y + 6z
A = np.zeros((3,3),dtype=int)
A[0][0] = 3
A[0][1] = -1
A[1][0] = 1
A[1][1] = 4
A[1][2] = -1
A[2][1] = 1
A[2][2] = 6

print("\nCoefficients matrix: \n",A)

print("\nConstants: \n",A@soln)

Variables: 
 [-4.   2.   7.5]

Coefficients matrix: 
 [[ 3 -1  0]
 [ 1  4 -1]
 [ 0  1  6]]

Constants: 
 [-14.   -3.5  47. ]
