In [11]:
# D. Scott
# Linear Algebra: TCI
# Code Challenge 10.2
# Examine RREF of square, wide, tall random matrices

import random
import numpy as np
import sympy as sym

# generate square, wide, tall random matrices
num1 = []
num2 = []
num3 = []
for i in range(0,9):
    num1.append(random.randint(-6,12))
for i in range(0,15):
    num2.append(random.randint(-6,12))
for i in range(0,12):
    num3.append(random.randint(-6,12))
A1 = np.array(num1).reshape(3,3)
A2 = np.array(num2).reshape(3,5)
A3 = np.array(num3).reshape(6,2)

print("Square:\n",A1)
print("\nWide:\n",A2)
print("\nTall:\n",A3)

print("\nSquare RREF: \n",sym.Matrix(A1).rref())
print("\nWide RREF: \n",sym.Matrix(A2).rref())
print("\nTall RREF: \n",sym.Matrix(A3).rref())

Square:
 [[ 3 -1 -3]
 [-5 -4  4]
 [ 8 -1 -5]]

Wide:
 [[ 8  2  9 -2 12]
 [ 3  8  2  9  3]
 [-4  8 -4  8  0]]

Tall:
 [[-5  9]
 [-3 12]
 [ 1 -4]
 [ 9  7]
 [ 2 11]
 [ 1  9]]

Square RREF: 
 (Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))

Wide RREF: 
 (Matrix([
[1, 0, 0,   17/8, -21/8],
[0, 1, 0,  29/32, 15/32],
[0, 0, 1, -37/16, 57/16]]), (0, 1, 2))

Tall RREF: 
 (Matrix([
[1, 0],
[0, 1],
[0, 0],
[0, 0],
[0, 0],
[0, 0]]), (0, 1))
