In [7]:
# D. Scott
# Linear Algebra: TCI
# Code Challenge 12.2
# Test pseudoinverse for full-rank square and full column rank rectangular matrices

import random
import numpy as np

# generate random test matrices
num1 = []
num2 = []
for i in range(0,25):
    num1.append(np.random.randint(-3,12))
for i in range(0,18):
    num2.append(np.random.randint(-3,12))
square = np.array(num1).reshape(5,5)
tall = np.array(num2).reshape(6,3)

print("Square:\n",square)
print("\nInverse (square):\n",np.linalg.inv(square))
print("\nPseudoinverse (square):\n",np.linalg.pinv(square))

print("\nTall:\n",tall)
left_inv = np.linalg.inv((tall.transpose()@tall))@tall.transpose()
print("\nLeft inverse (tall):\n",left_inv)
print("\nPseudoinverse (tall):\n",np.linalg.pinv(tall))

Square:
 [[ 2 -2  4 -1  9]
 [10  8  1 10 -3]
 [ 6  3  8 -3 -2]
 [ 9  1 11 11 -1]
 [ 5  0  4  7  2]]

Inverse (square):
 [[-0.29061811 -0.13185666  0.34454366 -0.56001392  1.17453323]
 [ 0.3346863   0.24921721 -0.26510495  0.47094979 -1.16189261]
 [ 0.16200858  0.04198075 -0.11585295  0.33573002 -0.61405543]
 [ 0.06215934  0.04975067 -0.1511075   0.17963586 -0.26638061]
 [ 0.18497043  0.07155282 -0.10077699  0.09984924 -0.27589006]]

Pseudoinverse (square):
 [[-0.29061811 -0.13185666  0.34454366 -0.56001392  1.17453323]
 [ 0.3346863   0.24921721 -0.26510495  0.47094979 -1.16189261]
 [ 0.16200858  0.04198075 -0.11585295  0.33573002 -0.61405543]
 [ 0.06215934  0.04975067 -0.1511075   0.17963586 -0.26638061]
 [ 0.18497043  0.07155282 -0.10077699  0.09984924 -0.27589006]]

Tall:
 [[ 2  2  6]
 [ 2 -2 10]
 [-2 11  9]
 [ 5  8  4]
 [ 7  1  0]
 [ 3 -3  4]]

Left inverse (tall):
 [[ 0.01009338 -0.00042768 -0.04003186  0.05144764  0.08138673  0.02455317]
 [-0.00409866 -0.04207816  0.04434375  0.04