In [19]:
# D. Scott
# Linear Algebra: TCI
# Code Challenge 6.2
# Compare diagonals of normal and Hadamard products

import random
import numpy as np

nums1 = []
nums2 = []

# generate random numbers
for i in range(0,16):
    r_num = 0
    while (r_num == 0):
        r_num = random.randint(-4,12)
    nums2.append(r_num)

# generate dense 4 x 4 matrix
m2 = np.array([[nums2[0],nums2[1],nums2[2],nums2[3]],
               [nums2[4],nums2[5],nums2[6],nums2[7]],
               [nums2[8],nums2[9],nums2[10],nums2[11]],
               [nums2[12],nums2[13],nums2[14],nums2[15]]])

m1 = np.empty((4,4),dtype=int)

# generate diagonal 4 x 4 matrix
for i in range(0,4):
    for j in range(0,4):
        r_num = 0
        while (r_num == 0):
            r_num = random.randint(-4,12)        
        if (i == j):
            m1[i][j] = r_num
        else:
            m1[i][j] = 0

print("Diagonal matrix:\n",m1,"\n")
print("Dense matrix:\n",m2,"\n")

print("Standard multiplication:\n",m1@m2,"\n\tDiag: ",np.diag(m1@m2),"\n")
print("Hadamard multiplication:\n",m1*m2,"\n\tDiag: ",np.diag(m1*m2),"\n")

print("The two different products have the same diagonals.")

Diagonal matrix:
 [[ 5  0  0  0]
 [ 0  7  0  0]
 [ 0  0 -1  0]
 [ 0  0  0 12]] 

Dense matrix:
 [[-2  3  3 12]
 [ 7  8 12 -3]
 [11 10 11  9]
 [11  8 10  7]] 

Standard multiplication:
 [[-10  15  15  60]
 [ 49  56  84 -21]
 [-11 -10 -11  -9]
 [132  96 120  84]] 
	Diag:  [-10  56 -11  84] 

Hadamard multiplication:
 [[-10   0   0   0]
 [  0  56   0   0]
 [  0   0 -11   0]
 [  0   0   0  84]] 
	Diag:  [-10  56 -11  84] 

The two different products have the same diagonals.
